name: Package Issues to JSON

on:
  schedule:
    - cron: '0 0 * * *' # 每天运行一次
  workflow_dispatch: # 手动触发工作流
  issues:
    types: [opened, edited, closed] # 当 issue 被打开、编辑或关闭时触发

jobs:
  package_issues:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Fetch issues from GitHub API
      id: fetch_issues
      run: |
        curl -s -H "Accept: application/vnd.github.v3+json" \
        "https://api.github.com/repos/${{ github.repository }}/issues?state=open&labels=友链提交" \
        | jq '[.[] | .body]' \
        > issues.json

    - name: Save issues to JSON file
      run: |
        mkdir -p data/json
        mv issues.json data/json/issues.json

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add data/json/issues.json
        git commit -m 'Update issues.json with open issues tagged with 友链提交'
        git push